sudo: false
# Trusty is required for HHVM
# Note: Trusty with 'sudo: false' (containers) are still in Beta
# https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/
dist: trusty
language: php
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "hhvm"
install:
  - composer install
  # Upgrade default Node.js version in Travis' PHP image from Node.js v0.10.x to v7.x
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash;
  - source ~/.nvm/nvm.sh; nvm install v7
script:
  - composer test
after_success:
  - php vendor/bin/coveralls -v
notifications:
  irc:
    channels:
      - "chat.freenode.net#mediawiki-i18n"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}: %{author}) %{message} - %{build_url}"
