language: php
php:
  - "7.2"
  - "7.3"
  - "7.4"
install:
  - composer install
  # Upgrade from default Node.js version in Travis' PHP image to 10.x
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
  - source ~/.nvm/nvm.sh; nvm install 10
script:
  - composer test
after_success:
  - php vendor/bin/php-coveralls -v
notifications:
  irc:
    channels:
      - "chat.freenode.net#mediawiki-i18n"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}: %{author}) %{message} - %{build_url}"
